version: '3'
services:
  mongodb:
    container_name: mongodb-${teamname:-defaultASW}
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
    
  questiongeneratorservice:
    container_name: qgservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/questiongenerator:latest
    profiles: ["dev", "prod"]
    build: ./game/qgservice
    depends_on:
      - mongodb
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
  
  gameservice:
    container_name: gameservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/gameservice:latest
    profiles: ["dev", "prod"]
    build: ./game/gameservice
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  groupservice:
    container_name: groupservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/groupservice:latest
    profiles: ["dev", "prod"]
    build: ./game/groupservice
    depends_on:
      - mongodb
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb
    
  multiplayerservice:
    container_name: multiplayerservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/multiplayerservice:latest
    profiles: ["dev", "prod"]
    build: ./multiplayerservice
    depends_on:
      - mongodb
    ports:
      - "8006:8006"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  gatewayservice:
    container_name: gatewayservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - questiongeneratorservice
      - gameservice
      - groupservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      QG_SERVICE_URL: http://questiongeneratorservice:8003
      GAME_SERVICE_URL: http://gameservice:8004
      GROUP_SERVICE_URL: http://groupservice:8005
      MULTIPLAYER_SERVICE_URL: http://multiplayerservice:8006

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_en2a/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
      - gatewayservice
    ports:
      - "80:80" 

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
